#!/bin/bash
#ovpn_genconfig -u udp://$(curl -s http://whatismyip.akamai.com/ | cut -b 1-16)
#ovpn_initpki
# populate environment datas into smtp config file
ssmtpc=/etc/ssmtp/ssmtp.conf 
cat << EOF > $ssmtpc
#gmail example
#AuthPass=[usual gmail pwd] # aint' gonna work
#[pwd generated by https://myaccount.google.com/apppasswords]
root=$EmailUN
AuthUser=$EmailUN
AuthPass=$EmailPW
mailhub=$SMTP
#mailhub=smtp.gmail.com:465
#UseSTARTTLS=Yes
#UseTLS=YES
$TLS
$STARTLS
EOF